### ISSUE TITLE
Consistent Function names.

### ISSUE THREAD

**Issue by donnyh13** [donnyh13/Au3LibreOffice#111]
### Feature Request Name: 
**	|-->: Consistent Function names.

### Brief Description: 
**	|-->: Functions that are supposed to return an array of names for certain things aren't named consistently.

### Is your feature request related to a problem? 
** Yes [x] <br>
** No [ ] 

### Please describe

A clear and concise description of what the problem is. For example: I'm always frustrated when [...] . <br>
**	|-->: I have been inconsistent in function naming for functions designed to return an array of names or objects, e.g.
- _LOCalc_CellStyles**GetNames**
- _LOCalc_Comments**GetList**
- _LOCalc_Doc**Enum**Printers
- _LOCalc_Fonts**List**

### Describe the solution you'd like implemented

A clear and concise description of what you want to happen. <br>
**	|-->: I would like to rename all such functions to have a uniform name such as 
- _LOCalc_CellStylesGet**List**
- _LOCalc_CommentsGetList
- _LOCalc_DocPrinters**GetList**
- _LOCalc_Fonts**Get**List

### Describe alternatives you've considered

A clear and concise description of any alternative solutions or features you've considered. <br>
**	|-->: Any other variety could be chosen, GetNames, GetList, List. Or we could leave them as they are.

### Additional context

Add any other context or screenshots about the feature request here. <br>
**	|-->:

### Influences and relationship to other functionality

Describe how the changes will affect other functions, potential script breaking changes, etc. <br>
**	|-->: Renaming  the problematic functions would cause **script breaking** changes. Though the amount would be few between the last release and the next one, mainly the script breaking changes would be if anyone used the main unreleased files.

**Comment by donnyh13** [comment]
Another option would be to name the functions returning Strings/Names to "GetNames" and the ones returning Objects to "GetList". This would probably lessen the number of Script Breaking changes.

**Comment by mlipok** [comment]
Should this be closed ? I mean as the #112 was merged.

**Comment by donnyh13** [comment]
Yes. Thank you.
