### ISSUE TITLE
Const description from function headers should be moved to LibreOfficeWriter_Constants.au3

### ISSUE THREAD

**Issue by mlipok** [donnyh13/Au3LibreOffice#18]
> This is first time when Const description from function headers are moved to LibreOfficeWriter_Constants.au3
              > 
              > All others cases should be similarly changed.

  > Should be done in the future.

_Originally posted by @mlipok in https://github.com/mlipok/Au3LibreOffice/issues/17#issuecomment-1737441763_

**Comment by donnyh13** [comment]
I see you wish for them to be deleted from below funcs. Will go back and do that. May need to adjust Const descs I added in LibreOfficeWriter_Constants.au3.

**Comment by donnyh13** [comment]
How do you want to list which Constants are accepted? Some don't accept them all, such as _LOWriter_FieldRefEndnoteInsert in LibreOfficeWriter_Field.au3, it only accepts Consts. 1-4

**Comment by mlipok** [comment]
> How do you want to list which Constants are accepted? Some don't accept them all, such as _LOWriter_FieldRefEndnoteInsert in LibreOfficeWriter_Field.au3, it only accepts Consts. 1-4


take a look here: https://github.com/mlipok/Au3LibreOffice/pull/39

EDIT
oops.
forget to merge.

So again here: https://github.com/mlipok/Au3LibreOffice/pull/40

**Comment by mlipok** [comment]
also https://github.com/mlipok/Au3LibreOffice/pull/41

**Comment by donnyh13** [comment]
Done —  #43

**Comment by mlipok** [comment]
after merging #43   
This issue should be reviewed

**Comment by donnyh13** [comment]
You mean double check for anything missed?

**Comment by mlipok** [comment]
Something like.

**Comment by mlipok** [comment]
I think most if not all of it is already done.
So we will act on an ongoing basis when we find something, instead of focusing on checking all functions from top to bottom.

**Comment by donnyh13** [comment]
Okay. 
I am doing another go through currently. I did find some I missed. I'm half way through the files so far. Can do a P.R. now, or when I'm done. which ever you prefer.

**Comment by donnyh13** [comment]
Okay. 
I am in the middle of doing another go through currently. I did find some I missed, and also some errors that needed corrected in the headers. I'm half way through the files so far. Can do a P.R. now, or when I'm done. Which ever you prefer.
