### ISSUE TITLE
Header Length

### ISSUE THREAD

**Issue by donnyh13** [donnyh13/Au3LibreOffice#34]
Are you not concerned that the UDF Spec states

> The header is 129 characters wide, and any text within it should be wrapped to that length. ...... The exception to that rule is the >Syntax line, which should not be wrapped.

https://www.autoitscript.com/wiki/UDF-spec#Headers

**Comment by mlipok** [comment]
This is old recomendation. Will answer more in the coming next few days.
Currently from phone.

**Comment by donnyh13** [comment]
Okay sounds good.

**Comment by mlipok** [comment]
I asked a question on the AutoIt forum in the MVP section (not visible for standard user).
https://www.autoitscript.com/forum/topic/210902-wiki-udf-spec-question-about-header-length

**Comment by donnyh13** [comment]
Okay. Let me know what they say.

**Comment by donnyh13** [comment]
Any replies to this?
