### ISSUE TITLE
Cell Functions in LibreOfficeWriter file.

### ISSUE THREAD

**Issue by donnyh13** [donnyh13/Au3LibreOffice#36]
Would it not be more logical to place the Cell functions from LibreOfficeWriter.au3 to LibreOfficeWriter_Table.au3 ?

**Comment by mlipok** [comment]
soon, not all at once.

**Comment by mlipok** [comment]
done. Take a look on: https://github.com/mlipok/Au3LibreOffice/pull/37


What do you think about:
```
; _LOWriter_SearchDescriptorCreate
; _LOWriter_SearchDescriptorModify
; _LOWriter_SearchDescriptorSimilarityModify
; _LOWriter_ShapesGetNames
```

btw.
I plan to rename main file `LibreOfficeWriter.au3` >> `LibreOffice.au3`

**Comment by mlipok** [comment]
Do you plan in a future that there will be more `_LOWriter_Shapes*****` functions ?

**Comment by donnyh13** [comment]
I like the changes you’ve made and suggested so far, the splits look great. 

 As for the Search Descriptors, I don’t know, it belongs functionally with the findNext, Findall etc. functions, as well as the FindFormat functions, we could rename the Search Desc functions if you want, to make them “fit” with the rest? Otherwise maybe they could be moved to helper? 
As for shapes, yes, I have planned to add functions for them, (inserting modifying etc.,) it will probably be my next project step after I get done the current batch I’m working on, currently I have about 10 or so Image functions about 90% done. I need to test them, and add headers to several, and create examples for all. After that, I will work on shapes, at least I plan to. But first I need to finish the cleaning you’ve requested, which I believe I’m nearing over half done. 
Thanks again for the cleaning you’ve done, and the suggestions, I appreciate the time you’ve take to look through it all, and split it down to manageable sizes. I attempted to keep everything in alignment in the headers, but I ended up doing several find and replace for certain variable names and it threw them off, and I never found time to correct them.
	Before I post the new functions (when I get them done), is there any of my coding practices that you would like me to change?

**Comment by donnyh13** [comment]
> I plan to rename main file LibreOfficeWriter.au3 >> LibreOffice.au3

What do you plan to use  LibreOffice.au3 for? Main creation/ management funcs applicable for all components of L.O.?

**Comment by mlipok** [comment]
> Main creation/ management funcs applicable for all components of L.O.?

Yes.
Also one Include to add support for entire LibreOffice SDK/API

**Comment by donnyh13** [comment]
Okay. Good idea.
