### ISSUE TITLE
preparation of the release

### ISSUE THREAD

**Issue by mlipok** [donnyh13/Au3LibreOffice#55]
We should start to think about new release.

- [x] We should do it like [@danp2](https://github.com/Danp2) is in habbit to do it.
Example:
https://github.com/Danp2/au3WebDriver/compare/1.1.1...1.2.0
https://github.com/Danp2/au3WebDriver/commit/0ade2bbd52fdc9ebda4fe9e42c69ff63d9494813

- [x] We should move https://github.com/mlipok/Au3LibreOffice/blob/main/Changes.log to CHANGELOG.md
Example:
https://github.com/Danp2/au3WebDriver/blob/master/CHANGELOG.md

- [x] We should add templates: bug_report.md
Example:
https://github.com/Danp2/au3WebDriver/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

- [x] We should add templates: feature_request.md
Example: 
https://github.com/Danp2/au3WebDriver/blob/master/.github/ISSUE_TEMPLATE/feature_request.md

- [x] We should add : PULL_REQUEST_TEMPLATE.md
Example:
https://github.com/Danp2/au3WebDriver/blob/master/PULL_REQUEST_TEMPLATE.md

- [x] We should add : CODE_OF_CONDUCT.md
Example: 
https://github.com/Danp2/au3WebDriver/blob/master/CODE_OF_CONDUCT.md

- [x] We should add : CONTRIBUTING.md
Example: 
https://github.com/Danp2/au3WebDriver/blob/master/docs/CONTRIBUTING.md

**Comment by donnyh13** [comment]
Okay, will look into it.

Edit
Danp2's documentation does look very good. Will try to use that style from now on. It will take some getting used to. :)

**Comment by donnyh13** [comment]
In your eyes, are we ready to release a version 1.0.0 by now? or should we stay in 0.x.x  for a version? Or shall we count all previous releases and release it as Version 4.0.0?

**Comment by mlipok** [comment]
We are close to 1.0.0

**Comment by donnyh13** [comment]
Okay. Will work on creating the documentation.

**Comment by donnyh13** [comment]
I would like to suggest we also add sections/headers in the Changelog per component (Writer,Calc, etc), when we get to the point we have more than one component available.

**Comment by donnyh13** [comment]
See what you think: #56
