### ISSUE TITLE
_LOWriter_DocFindAllInRange : _LOWriter_DocGetViewCursor and _LOWriter_DocCreateTextCursor  usage

### ISSUE THREAD

**Issue by mlipok** [donnyh13/Au3LibreOffice#7]
why `_LOWriter_DocFindAllInRange` just simpy use this:

```autoit
	_LOWriter_DocGetViewCursor
	_LOWriter_DocCreateTextCursor
```
and like not this:
```autoit
	_LOWriter_DocGetViewCursor()
	_LOWriter_DocCreateTextCursor()
```

**Comment by mlipok** [comment]
the same with:
_LOWriter_DocGenPropTemplate : _LOWriter_DateStructModify usage

**Comment by donnyh13** [comment]
Both issues listed have no usage in the script, May be accidental left overs from testing. Can be safely removed.
In _LOWriter_DocFindAllInRange
Both _LOWriter_DocGetViewCursor
	_LOWriter_DocCreateTextCursor
Do not belong.

In _LOWriter_DocGenPropTemplate 
_LOWriter_DateStructModify does not belong
