### ISSUE TITLE
LibreOfficeWriter_DirectFormating.au3 Misspelled 

### ISSUE THREAD

**Issue by donnyh13** [donnyh13/Au3LibreOffice#89]
### Bug Report Name: 
**	|-->:

### Brief Description: 
**	|-->:
- The file LibreOfficeWriter_DirectFormating.au3, is misspelled.
- Should be named: LibreOfficeWriter_DirectFormatting.au3

### Describe the bug 

A clear and concise description of what the bug is. <br>
**	|-->:

### How to reproduce 

Steps to reproduce the behavior (e.g.):

2. Call function '...' with '...' 
3. Wrong action occurred or error received

### Expected behavior

A clear and concise description of what you expected to happen. <br>
**	|-->:

### Screenshots

If applicable, add screenshots to help explain your problem. <br>

### Additional context

Add any other context about the problem here. <br>
**	|-->: Not sure if you want to rename it or not?

### System under test

Please complete the following information.

- OS: [e.g. Windows 10]
- OS Arch.: [e.g. X64]
- LibreOffice Component: [e.g. Writer, Calc]
- LibreOffice version: [e.g. 7.3.4.2]
- Au3LibreOffice Version: [e.g. 0.0.0.3]

**Comment by mlipok** [comment]
I just merge: https://github.com/mlipok/Au3LibreOffice/pull/90

If no more issue here please close this issue.
